//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.06 at 03:55:35 PM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.dxc.com/spring/soap/api/loaneligibility", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.dxc.spring.soap.api.loaneligibility;
